//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResJavascript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResJavascript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestApplication.Resources.ResJavascript", typeof(ResJavascript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substring test for slots {0} and then {1} and then {10} and lastly {01}..
        /// </summary>
        internal static string TestWithIntegerParameterSubstring {
            get {
                return ResourceManager.GetString("TestWithIntegerParameterSubstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the first {first} and this is the {second}..
        /// </summary>
        internal static string TestWithNamedParameter {
            get {
                return ResourceManager.GetString("TestWithNamedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the first {first} and this is the {second} and this is {firstsecond} with {secondfirst}..
        /// </summary>
        internal static string TestWithNamedParameterWithSubstring {
            get {
                return ResourceManager.GetString("TestWithNamedParameterWithSubstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter zero {0} has been used twice here {0}..
        /// </summary>
        internal static string TestWithSameParameterUsedTwice {
            get {
                return ResourceManager.GetString("TestWithSameParameterUsedTwice", resourceCulture);
            }
        }
    }
}
